"""SQLAlchemy models for multi-channel alert engine."""

import enum
from datetime import datetime, timezone
from typing import Any, Dict, Optional

from sqlalchemy import (
    Enum as SAEnum,
    ForeignKey,
    String,
    Text,
    DateTime,
    JSON,
)
from sqlalchemy.orm import Mapped, mapped_column

from packages.core.db.base import Base, UUIDMixin, TimestampMixin


class AlertSeverity(str, enum.Enum):
    """Alert severity classification."""

    INFO = "INFO"
    WARNING = "WARNING"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class AlertStatus(str, enum.Enum):
    """Alert lifecycle state."""

    OPEN = "OPEN"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    RESOLVED = "RESOLVED"


class Alert(Base, UUIDMixin, TimestampMixin):
    """An incident or anomaly event generated by the monitoring system."""

    __tablename__ = "alerts"

    project_id: Mapped[str | None] = mapped_column(
        String(36), ForeignKey("projects.id", ondelete="SET NULL"), nullable=True, index=True
    )
    model_name: Mapped[str | None] = mapped_column(
        String(200), nullable=True, index=True
    )
    deployment_id: Mapped[str | None] = mapped_column(
        String(36), ForeignKey("deployments.id", ondelete="SET NULL"), nullable=True, index=True
    )
    event_type: Mapped[str] = mapped_column(
        String(100), nullable=False, doc="Event type: DATA_DRIFT, PERFORMANCE_DROP, CONTAINER_CRASH, LATENCY_SPIKE"
    )
    severity: Mapped[AlertSeverity] = mapped_column(
        SAEnum(AlertSeverity, name="alert_severity", create_constraint=True),
        default=AlertSeverity.WARNING,
        nullable=False,
    )
    title: Mapped[str] = mapped_column(
        String(300), nullable=False
    )
    message: Mapped[str] = mapped_column(
        Text, nullable=False
    )
    details_json: Mapped[dict | None] = mapped_column(
        JSON, nullable=True, doc="Metric scores, feature names, or stack traces"
    )
    status: Mapped[AlertStatus] = mapped_column(
        SAEnum(AlertStatus, name="alert_status", create_constraint=True),
        default=AlertStatus.OPEN,
        server_default="OPEN",
        nullable=False,
    )
    acknowledged_by: Mapped[str | None] = mapped_column(
        String(100), nullable=True
    )
    resolved_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
